// Generated by tools/generate.py from algorithm/cpu_performance.json.
// Do not edit by hand.

#include "cpu_performance_tier.h"

#include <cstdlib>
#include <iostream>
#include <string>

using namespace cpu_performance_tier;

std::string ToString(PerformanceTier tier) { return std::to_string(static_cast<int>(tier)); }
std::string ToString(Manufacturer manufacturer) { return std::to_string(static_cast<int>(manufacturer)); }

int main() {
  int failures = 0;
  if (TierFromCores(1) != PerformanceTier::Low) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(2) != PerformanceTier::Low) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(3) != PerformanceTier::Mid) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(4) != PerformanceTier::Mid) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(5) != PerformanceTier::High) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(8) != PerformanceTier::High) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(12) != PerformanceTier::High) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(13) != PerformanceTier::Ultra) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(16) != PerformanceTier::Ultra) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(96) != PerformanceTier::Ultra) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(0) != PerformanceTier::Unknown) { std::cerr << "core test failed\n"; ++failures; }
  if (TierFromCores(-42) != PerformanceTier::Unknown) { std::cerr << "core test failed\n"; ++failures; }
  {
    auto result = SplitCpuModel("Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz");
    if (result.first != Manufacturer::Intel || result.second != "Core i7-10700K") { std::cerr << "split test failed: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Intel® Core™i7-8600HQ CPU @ 3.0GHz");
    if (result.first != Manufacturer::Intel || result.second != "Core i7-8600HQ") { std::cerr << "split test failed: Intel® Core™i7-8600HQ CPU @ 3.0GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Intel(R) Processor 5Y70 CPU @ 1.10GHz");
    if (result.first != Manufacturer::Intel || result.second != "5Y70") { std::cerr << "split test failed: Intel(R) Processor 5Y70 CPU @ 1.10GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz");
    if (result.first != Manufacturer::Intel || result.second != "Core i3-330M") { std::cerr << "split test failed: Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Intel(R) Core(TM)2 Duo CPU     E4300  @ 1.80GHz");
    if (result.first != Manufacturer::Intel || result.second != "Core 2 Duo E4300") { std::cerr << "split test failed: Intel(R) Core(TM)2 Duo CPU     E4300  @ 1.80GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Intel(R) Core(TM) i7 CPU       L 620  @ 2.00GHz");
    if (result.first != Manufacturer::Intel || result.second != "Core i7-620LM") { std::cerr << "split test failed: Intel(R) Core(TM) i7 CPU       L 620  @ 2.00GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Intel(R) Core i5 - 10500u (tm) Processor");
    if (result.first != Manufacturer::Intel || result.second != "Core i5-10500u") { std::cerr << "split test failed: Intel(R) Core i5 - 10500u (tm) Processor" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Celeron(R) Dual-Core CPU       T3000  @ 1.80GHz");
    if (result.first != Manufacturer::Intel || result.second != "Celeron T3000") { std::cerr << "split test failed: Celeron(R) Dual-Core CPU       T3000  @ 1.80GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD Ryzen 7 5800X 8-Core Processor");
    if (result.first != Manufacturer::Amd || result.second != "Ryzen 7 5800X") { std::cerr << "split test failed: AMD Ryzen 7 5800X 8-Core Processor" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx");
    if (result.first != Manufacturer::Amd || result.second != "Ryzen 5 3500U") { std::cerr << "split test failed: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD A4-9120e RADEON R3, 4 COMPUTE CORES 2C+2G");
    if (result.first != Manufacturer::Amd || result.second != "A4-9120e") { std::cerr << "split test failed: AMD A4-9120e RADEON R3, 4 COMPUTE CORES 2C+2G" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD A10-4600M APU with Radeon(tm) HD Graphics");
    if (result.first != Manufacturer::Amd || result.second != "A10-4600M") { std::cerr << "split test failed: AMD A10-4600M APU with Radeon(tm) HD Graphics" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD FX(tm)-4130 Quad-Core Processor");
    if (result.first != Manufacturer::Amd || result.second != "FX-4130") { std::cerr << "split test failed: AMD FX(tm)-4130 Quad-Core Processor" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD Ryzen 3 3250C 15W with Radeon Graphics");
    if (result.first != Manufacturer::Amd || result.second != "Ryzen 3 3250C") { std::cerr << "split test failed: AMD Ryzen 3 3250C 15W with Radeon Graphics" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD Ryzen 5 6600HS Creator Edition");
    if (result.first != Manufacturer::Amd || result.second != "Ryzen 5 6600HS") { std::cerr << "split test failed: AMD Ryzen 5 6600HS Creator Edition" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD Turion(tm) 64 Mobile Technology MK-36");
    if (result.first != Manufacturer::Amd || result.second != "Turion 64 MK-36") { std::cerr << "split test failed: AMD Turion(tm) 64 Mobile Technology MK-36" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("AMD® Ryzen™5  3450U Quad Core@");
    if (result.first != Manufacturer::Amd || result.second != "Ryzen 5 3450U") { std::cerr << "split test failed: AMD® Ryzen™5  3450U Quad Core@" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Apple M1 ");
    if (result.first != Manufacturer::Apple || result.second != "M1") { std::cerr << "split test failed: Apple M1 " << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Apple M2 Pro (Virtual)");
    if (result.first != Manufacturer::Apple || result.second != "M2 Pro") { std::cerr << "split test failed: Apple M2 Pro (Virtual)" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Microsoft SQ2 @ 3.15 GHz");
    if (result.first != Manufacturer::Microsoft || result.second != "") { std::cerr << "split test failed: Microsoft SQ2 @ 3.15 GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Oryon(TM) CPU");
    if (result.first != Manufacturer::Qualcomm || result.second != "") { std::cerr << "split test failed: Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Oryon(TM) CPU" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Snapdragon (TM) 7c @ 2.40 GHz");
    if (result.first != Manufacturer::Qualcomm || result.second != "") { std::cerr << "split test failed: Snapdragon (TM) 7c @ 2.40 GHz" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("MediaTek Dimensity 9200");
    if (result.first != Manufacturer::MediaTek || result.second != "") { std::cerr << "split test failed: MediaTek Dimensity 9200" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Samsung Exynos 2100");
    if (result.first != Manufacturer::Samsung || result.second != "") { std::cerr << "split test failed: Samsung Exynos 2100" << " got '" << result.second << "'\n"; ++failures; }
  }
  {
    auto result = SplitCpuModel("Unknown CPU");
    if (result.first != Manufacturer::Unknown || result.second != "") { std::cerr << "split test failed: Unknown CPU" << " got '" << result.second << "'\n"; ++failures; }
  }
  if (TierFromCpuInfo("Some imaginary processor", -42) != PerformanceTier::Unknown) { std::cerr << "tier test failed: Some imaginary processor\n"; ++failures; }
  if (TierFromCpuInfo("Some unknown processor", 0) != PerformanceTier::Unknown) { std::cerr << "tier test failed: Some unknown processor\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Celeron(R) CPU          450  @ 2.20GHz", 1) != PerformanceTier::Low) { std::cerr << "tier test failed: Intel(R) Celeron(R) CPU          450  @ 2.20GHz\n"; ++failures; }
  if (TierFromCpuInfo("AMD Athlon(tm) Processor 1640B", 1) != PerformanceTier::Low) { std::cerr << "tier test failed: AMD Athlon(tm) Processor 1640B\n"; ++failures; }
  if (TierFromCpuInfo("AMD E2-9000e RADEON R2, 4 COMPUTE CORES 2C+2G", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: AMD E2-9000e RADEON R2, 4 COMPUTE CORES 2C+2G\n"; ++failures; }
  if (TierFromCpuInfo("AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G\n"; ++failures; }
  if (TierFromCpuInfo("AMD Athlon(tm) 64 X2 Dual Core Processor 5000+", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: AMD Athlon(tm) 64 X2 Dual Core Processor 5000+\n"; ++failures; }
  if (TierFromCpuInfo("AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx", 4) != PerformanceTier::Mid) { std::cerr << "tier test failed: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx\n"; ++failures; }
  if (TierFromCpuInfo("AMD Ryzen 3 3100 4-Core Processor", 4) != PerformanceTier::High) { std::cerr << "tier test failed: AMD Ryzen 3 3100 4-Core Processor\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Atom(TM) CPU Z520   @ 1.33GHz", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: Intel(R) Atom(TM) CPU Z520   @ 1.33GHz\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Celeron(R) CPU J3355 @ 2.00GHz", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: Intel(R) Celeron(R) CPU J3355 @ 2.00GHz\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Pentium(R) CPU        P6100  @ 2.00GHz", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: Intel(R) Pentium(R) CPU        P6100  @ 2.00GHz\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Celeron(R) CPU B830 @ 1.80GHz", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: Intel(R) Celeron(R) CPU B830 @ 1.80GHz\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Celeron(R) N4000 CPU @ 1.10GHz", 2) != PerformanceTier::Mid) { std::cerr << "tier test failed: Intel(R) Celeron(R) N4000 CPU @ 1.10GHz\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Celeron(R) CPU  N3160  @ 1.60GHz", 4) != PerformanceTier::Low) { std::cerr << "tier test failed: Intel(R) Celeron(R) CPU  N3160  @ 1.60GHz\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) N100", 4) != PerformanceTier::High) { std::cerr << "tier test failed: Intel(R) N100\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Atom(TM) x7425E", 4) != PerformanceTier::High) { std::cerr << "tier test failed: Intel(R) Atom(TM) x7425E\n"; ++failures; }
  if (TierFromCpuInfo("11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz", 8) != PerformanceTier::High) { std::cerr << "tier test failed: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Core(TM) Ultra 5 226V", 8) != PerformanceTier::Ultra) { std::cerr << "tier test failed: Intel(R) Core(TM) Ultra 5 226V\n"; ++failures; }
  if (TierFromCpuInfo("Intel(R) Core(TM) Ultra 7 155H", 16) != PerformanceTier::Ultra) { std::cerr << "tier test failed: Intel(R) Core(TM) Ultra 7 155H\n"; ++failures; }
  if (TierFromCpuInfo("Apple A18 Pro", 6) != PerformanceTier::High) { std::cerr << "tier test failed: Apple A18 Pro\n"; ++failures; }
  if (TierFromCpuInfo("Apple M1", 8) != PerformanceTier::Ultra) { std::cerr << "tier test failed: Apple M1\n"; ++failures; }
  if (TierFromCpuInfo("Snapdragon(R) X Plus - X1P64100 - Qualcomm(R) Oryon(TM) CPU", 10) != PerformanceTier::High) { std::cerr << "tier test failed: Snapdragon(R) X Plus - X1P64100 - Qualcomm(R) Oryon(TM) CPU\n"; ++failures; }
  if (TierFromCpuInfo("Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Oryon(TM) CPU", 12) != PerformanceTier::Ultra) { std::cerr << "tier test failed: Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Oryon(TM) CPU\n"; ++failures; }
  if (TierFromCpuInfo("MediaTek Dimensity 9200", 8) != PerformanceTier::High) { std::cerr << "tier test failed: MediaTek Dimensity 9200\n"; ++failures; }
  if (TierFromCpuInfo("Samsung Exynos 2100", 8) != PerformanceTier::High) { std::cerr << "tier test failed: Samsung Exynos 2100\n"; ++failures; }
  if (TierFromCpuInfo("Unknown CPU", 2) != PerformanceTier::Low) { std::cerr << "tier test failed: Unknown CPU\n"; ++failures; }
  if (TierFromCpuInfo("Unknown CPU", 4) != PerformanceTier::Mid) { std::cerr << "tier test failed: Unknown CPU\n"; ++failures; }
  if (TierFromCpuInfo("Unknown CPU", 8) != PerformanceTier::High) { std::cerr << "tier test failed: Unknown CPU\n"; ++failures; }
  if (TierFromCpuInfo("Unknown CPU", 16) != PerformanceTier::Ultra) { std::cerr << "tier test failed: Unknown CPU\n"; ++failures; }
  return failures == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
}
