#!/usr/bin/env python3
# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import argparse
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "algorithm" / "cpu_performance.json"


def load():
    return json.loads(DATA.read_text())


def rs_str(value):
    return json.dumps(value, ensure_ascii=False)


def cpp_str(value):
    return json.dumps(value, ensure_ascii=False)


def generated_header():
    return "// Generated by tools/generate.py from algorithm/cpu_performance.json.\n// Do not edit by hand.\n\n"


def gen_rust(data):
    out = [generated_header()]
    out.append("#[derive(Clone, Copy)]\npub(crate) struct PatternRule {\n")
    out.append("    pub(crate) manufacturer: super::Manufacturer,\n")
    out.append("    pub(crate) min_cores: i32,\n")
    out.append("    pub(crate) max_cores: i32,\n")
    out.append("    pub(crate) tier: super::PerformanceTier,\n")
    out.append("    pub(crate) include: &'static [&'static str],\n")
    out.append("    pub(crate) exclude: &'static [&'static str],\n}\n\n")
    for i, rule in enumerate(data["rules"]):
        out.append(f"const INCLUDE_{i}: &[&str] = &[")
        out.append(", ".join(rs_str(v) for v in rule.get("include", [])))
        out.append("];\n")
        out.append(f"const EXCLUDE_{i}: &[&str] = &[")
        out.append(", ".join(rs_str(v) for v in rule.get("exclude", [])))
        out.append("];\n")
    out.append("\npub(crate) const PATTERN_RULES: &[PatternRule] = &[\n")
    for i, rule in enumerate(data["rules"]):
        out.append("    PatternRule { ")
        out.append(f"manufacturer: super::Manufacturer::{rule['manufacturer']}, ")
        out.append(f"min_cores: {rule['min_cores']}, max_cores: {rule['max_cores']}, ")
        out.append(f"tier: super::PerformanceTier::{rule['tier']}, ")
        out.append(f"include: INCLUDE_{i}, exclude: EXCLUDE_{i}")
        out.append(" },\n")
    out.append("];\n\n")

    out.append("#[cfg(test)]\npub(crate) const CORE_TESTS: &[(i32, super::PerformanceTier)] = &[\n")
    for cores, tier in data["core_tests"]:
        out.append(f"    ({cores}, super::PerformanceTier::{tier}),\n")
    out.append("];\n\n")

    out.append("#[cfg(test)]\npub(crate) const SPLIT_TESTS: &[(&str, super::Manufacturer, &str)] = &[\n")
    for model, manufacturer, normalized in data["split_tests"]:
        out.append(f"    ({rs_str(model)}, super::Manufacturer::{manufacturer}, {rs_str(normalized)}),\n")
    out.append("];\n\n")

    out.append("#[cfg(test)]\npub(crate) const TIER_CPU_INFO_TESTS: &[(i32, &str, super::PerformanceTier)] = &[\n")
    for cores, model, tier in data["tier_cpu_info_tests"]:
        out.append(f"    ({cores}, {rs_str(model)}, super::PerformanceTier::{tier}),\n")
    out.append("];\n")
    return "".join(out)


def gen_cpp_rules(data):
    out = [generated_header()]
    out.append("namespace cpu_performance_tier {\nnamespace generated {\n\n")
    out.append("const PatternRule kPatternRules[] = {\n")
    for rule in data["rules"]:
        includes = "{" + ", ".join(cpp_str(v) for v in rule.get("include", [])) + "}"
        excludes = "{" + ", ".join(cpp_str(v) for v in rule.get("exclude", [])) + "}"
        out.append("  {")
        out.append(f"Manufacturer::{rule['manufacturer']}, {rule['min_cores']}, {rule['max_cores']}, PerformanceTier::{rule['tier']}, ")
        out.append(f"{includes}, {excludes}")
        out.append("},\n")
    out.append("};\n\n")
    out.append("const size_t kPatternRuleCount = sizeof(kPatternRules) / sizeof(kPatternRules[0]);\n\n")
    out.append("}  // namespace generated\n}  // namespace cpu_performance_tier\n")
    return "".join(out)


def gen_cpp_tests(data):
    out = [generated_header()]
    out.append("#include \"cpu_performance_tier.h\"\n\n#include <cstdlib>\n#include <iostream>\n#include <string>\n\nusing namespace cpu_performance_tier;\n\n")
    out.append("std::string ToString(PerformanceTier tier) { return std::to_string(static_cast<int>(tier)); }\n")
    out.append("std::string ToString(Manufacturer manufacturer) { return std::to_string(static_cast<int>(manufacturer)); }\n\n")
    out.append("int main() {\n  int failures = 0;\n")
    for cores, tier in data["core_tests"]:
        out.append(f"  if (TierFromCores({cores}) != PerformanceTier::{tier}) {{ std::cerr << \"core test failed\\n\"; ++failures; }}\n")
    for model, manufacturer, normalized in data["split_tests"]:
        out.append("  {\n")
        out.append(f"    auto result = SplitCpuModel({cpp_str(model)});\n")
        out.append(f"    if (result.first != Manufacturer::{manufacturer} || result.second != {cpp_str(normalized)}) {{ std::cerr << \"split test failed: {model}\" << \" got '\" << result.second << \"'\\n\"; ++failures; }}\n")
        out.append("  }\n")
    for cores, model, tier in data["tier_cpu_info_tests"]:
        out.append(f"  if (TierFromCpuInfo({cpp_str(model)}, {cores}) != PerformanceTier::{tier}) {{ std::cerr << \"tier test failed: {model}\\n\"; ++failures; }}\n")
    out.append("  return failures == 0 ? EXIT_SUCCESS : EXIT_FAILURE;\n}\n")
    return "".join(out)


def write_or_check(path, content, check):
    path.parent.mkdir(parents=True, exist_ok=True)
    if check:
        old = path.read_text() if path.exists() else None
        if old != content:
            print(f"stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
            return False
        return True
    path.write_text(content)
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = load()
    ok = True
    rust = gen_rust(data)
    try:
        rust = subprocess.run(
            ["rustfmt", "--emit", "stdout"],
            input=rust,
            text=True,
            check=True,
            stdout=subprocess.PIPE,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        pass
    ok &= write_or_check(ROOT / "src" / "generated.rs", rust, args.check)
    ok &= write_or_check(ROOT / "cpp" / "generated_rules.inc", gen_cpp_rules(data), args.check)
    ok &= write_or_check(ROOT / "cpp" / "generated_tests.cc", gen_cpp_tests(data), args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
