// Generated by tools/generate.py from algorithm/cpu_performance.json.
// Do not edit by hand.

#[derive(Clone, Copy)]
pub(crate) struct PatternRule {
    pub(crate) manufacturer: super::Manufacturer,
    pub(crate) min_cores: i32,
    pub(crate) max_cores: i32,
    pub(crate) tier: super::PerformanceTier,
    pub(crate) include: &'static [&'static str],
    pub(crate) exclude: &'static [&'static str],
}

const INCLUDE_0: &[&str] = &[
    "^Athlon 64\\b",
    "^Athlon II\\b",
    "^Athlon X2\\b",
    "^Phenom II\\b",
    "^Sempron X2\\b",
    "^Turion II\\b",
    "^Turion X2\\b",
    "^(A4|E2)-[3]\\d\\d\\d[A-Z]*\\b",
    "^(A4|A6)-[4]\\d\\d\\dM[A-Z]*\\b",
];
const EXCLUDE_0: &[&str] = &[];
const INCLUDE_1: &[&str] = &[
    "^(C|E|E1|E2|T|Z)-\\w*\\b",
    "^(A4)-[1]\\d\\d\\d[A-Z]*\\b",
    "^(GX)-[2]\\d\\d[A-Z]*\\b",
    "^Sempron 2650\\b",
];
const EXCLUDE_1: &[&str] = &[];
const INCLUDE_2: &[&str] = &["^A4-9120[Ce]\\b"];
const EXCLUDE_2: &[&str] = &[];
const INCLUDE_3: &[&str] = &["^Ryzen\\b"];
const EXCLUDE_3: &[&str] = &[
    "^Ryzen 3 Pro 2100GE\\b",
    "^Ryzen 3 Pro 3050GE\\b",
    "^Ryzen 3 2200U\\b",
    "^Ryzen 3 3200U\\b",
    "^Ryzen 3 3250[UC]\\b",
    "^Ryzen Embedded R[1]\\d\\d\\d[A-Z]*\\b",
    "^Ryzen Embedded R2312\\b",
];
const INCLUDE_4: &[&str] = &[
    "^Atom (Z5)\\d\\d[A-Z]*\\b",
    "^Atom (2|3|N2)\\d\\d[A-Z]*\\b",
    "^Atom (D4|N4|D5|N5)\\d\\d[A-Z]*\\b",
    "^Atom (E6)\\d\\d[A-Z]*\\b",
    "^Atom (Z6)\\d\\d[A-Z]*\\b",
    "^Atom (D2|N2)\\d\\d\\d[A-Z]*\\b",
    "^Atom (Z2)\\d\\d\\d[A-Z]*\\b",
];
const EXCLUDE_4: &[&str] = &[];
const INCLUDE_5: &[&str] = &[
    "^Celeron (J1)\\d\\d\\d[A-Z]*\\b",
    "^Pentium (J2)\\d\\d\\d[A-Z]*\\b",
    "^Atom (C2)[35]\\d\\d[A-Z]*\\b",
    "^Atom (E3)[8]\\d\\d[A-Z]*\\b",
    "^Celeron (N2)\\d\\d\\d[A-Z]*\\b",
    "^Pentium (N3)[5]\\d\\d[A-Z]*\\b",
    "^Atom (Z3)\\d\\d\\d[A-Z]*\\b",
    "^Atom x[5]-(E8)\\d\\d\\d[A-Z]*\\b",
    "^Celeron (J3|N3)[01]\\d\\d[A-Z]*\\b",
    "^Pentium (J3|N3)[7]\\d\\d[A-Z]*\\b",
    "^Atom x[57]-(Z8)\\d\\d\\d[A-Z]*\\b",
];
const EXCLUDE_5: &[&str] = &[];
const INCLUDE_6: &[&str] = &[
    "^Atom x[5]-(A3|E3)\\d\\d\\d[A-Z]*\\b",
    "^Celeron (J3|N3)[34]\\d\\d[A-Z]*\\b",
    "^Atom (C3)\\d\\d\\d[A-Z]*\\b",
];
const EXCLUDE_6: &[&str] = &[];
const INCLUDE_7: &[&str] = &[
    "^Celeron (E1|SU2|T1|T3)\\d\\d\\d[A-Z]*\\b",
    "^Core 2 Duo\\b",
    "^Core 2 Extreme\\b",
    "^Pentium (E2|SU2|SU4|T2|T3|T4)\\d\\d\\d[A-Z]*\\b",
    "^Xeon (3|E3|L3)\\d\\d\\d[A-Z]*\\b",
];
const EXCLUDE_7: &[&str] = &[];
const INCLUDE_8: &[&str] = &[
    "^Celeron (P4|U3)\\d\\d\\d[A-Z]*\\b",
    "^Pentium (P6|U5)\\d\\d\\d[A-Z]*\\b",
];
const EXCLUDE_8: &[&str] = &[];
const INCLUDE_9: &[&str] = &[
    "^Celeron (7|8|B7|B8)\\d\\d[A-Z]*\\b",
    "^Pentium (9|B9)\\d\\d[A-Z]*\\b",
    "^Celeron (1)\\d\\d\\d[A-Z]*\\b",
    "^Pentium (2|A1)\\d\\d\\d[A-Z]*\\b",
];
const EXCLUDE_9: &[&str] = &[];
const INCLUDE_10: &[&str] = &["^N\\d\\d+\\b", "^Atom x7425E\\b"];
const EXCLUDE_10: &[&str] = &[];
const INCLUDE_11: &[&str] = &["^M\\d+\\b"];
const EXCLUDE_11: &[&str] = &[];
const INCLUDE_12: &[&str] = &["^Core Ultra\\b"];
const EXCLUDE_12: &[&str] = &[];

pub(crate) const PATTERN_RULES: &[PatternRule] = &[
    PatternRule {
        manufacturer: super::Manufacturer::Amd,
        min_cores: 2,
        max_cores: 2,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_0,
        exclude: EXCLUDE_0,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Amd,
        min_cores: 2,
        max_cores: 2,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_1,
        exclude: EXCLUDE_1,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Amd,
        min_cores: 2,
        max_cores: 2,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_2,
        exclude: EXCLUDE_2,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Amd,
        min_cores: 4,
        max_cores: 4,
        tier: super::PerformanceTier::High,
        include: INCLUDE_3,
        exclude: EXCLUDE_3,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Intel,
        min_cores: 2,
        max_cores: 4,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_4,
        exclude: EXCLUDE_4,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Intel,
        min_cores: 2,
        max_cores: 4,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_5,
        exclude: EXCLUDE_5,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Intel,
        min_cores: 2,
        max_cores: 2,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_6,
        exclude: EXCLUDE_6,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Intel,
        min_cores: 2,
        max_cores: 2,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_7,
        exclude: EXCLUDE_7,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Intel,
        min_cores: 2,
        max_cores: 2,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_8,
        exclude: EXCLUDE_8,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Intel,
        min_cores: 2,
        max_cores: 2,
        tier: super::PerformanceTier::Low,
        include: INCLUDE_9,
        exclude: EXCLUDE_9,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Intel,
        min_cores: 4,
        max_cores: 4,
        tier: super::PerformanceTier::High,
        include: INCLUDE_10,
        exclude: EXCLUDE_10,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Apple,
        min_cores: 8,
        max_cores: 10,
        tier: super::PerformanceTier::Ultra,
        include: INCLUDE_11,
        exclude: EXCLUDE_11,
    },
    PatternRule {
        manufacturer: super::Manufacturer::Intel,
        min_cores: 8,
        max_cores: 10,
        tier: super::PerformanceTier::Ultra,
        include: INCLUDE_12,
        exclude: EXCLUDE_12,
    },
];

#[cfg(test)]
pub(crate) const CORE_TESTS: &[(i32, super::PerformanceTier)] = &[
    (1, super::PerformanceTier::Low),
    (2, super::PerformanceTier::Low),
    (3, super::PerformanceTier::Mid),
    (4, super::PerformanceTier::Mid),
    (5, super::PerformanceTier::High),
    (8, super::PerformanceTier::High),
    (12, super::PerformanceTier::High),
    (13, super::PerformanceTier::Ultra),
    (16, super::PerformanceTier::Ultra),
    (96, super::PerformanceTier::Ultra),
    (0, super::PerformanceTier::Unknown),
    (-42, super::PerformanceTier::Unknown),
];

#[cfg(test)]
pub(crate) const SPLIT_TESTS: &[(&str, super::Manufacturer, &str)] = &[
    (
        "Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz",
        super::Manufacturer::Intel,
        "Core i7-10700K",
    ),
    (
        "Intel® Core™i7-8600HQ CPU @ 3.0GHz",
        super::Manufacturer::Intel,
        "Core i7-8600HQ",
    ),
    (
        "Intel(R) Processor 5Y70 CPU @ 1.10GHz",
        super::Manufacturer::Intel,
        "5Y70",
    ),
    (
        "Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz",
        super::Manufacturer::Intel,
        "Core i3-330M",
    ),
    (
        "Intel(R) Core(TM)2 Duo CPU     E4300  @ 1.80GHz",
        super::Manufacturer::Intel,
        "Core 2 Duo E4300",
    ),
    (
        "Intel(R) Core(TM) i7 CPU       L 620  @ 2.00GHz",
        super::Manufacturer::Intel,
        "Core i7-620LM",
    ),
    (
        "Intel(R) Core i5 - 10500u (tm) Processor",
        super::Manufacturer::Intel,
        "Core i5-10500u",
    ),
    (
        "Celeron(R) Dual-Core CPU       T3000  @ 1.80GHz",
        super::Manufacturer::Intel,
        "Celeron T3000",
    ),
    (
        "AMD Ryzen 7 5800X 8-Core Processor",
        super::Manufacturer::Amd,
        "Ryzen 7 5800X",
    ),
    (
        "AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx",
        super::Manufacturer::Amd,
        "Ryzen 5 3500U",
    ),
    (
        "AMD A4-9120e RADEON R3, 4 COMPUTE CORES 2C+2G",
        super::Manufacturer::Amd,
        "A4-9120e",
    ),
    (
        "AMD A10-4600M APU with Radeon(tm) HD Graphics",
        super::Manufacturer::Amd,
        "A10-4600M",
    ),
    (
        "AMD FX(tm)-4130 Quad-Core Processor",
        super::Manufacturer::Amd,
        "FX-4130",
    ),
    (
        "AMD Ryzen 3 3250C 15W with Radeon Graphics",
        super::Manufacturer::Amd,
        "Ryzen 3 3250C",
    ),
    (
        "AMD Ryzen 5 6600HS Creator Edition",
        super::Manufacturer::Amd,
        "Ryzen 5 6600HS",
    ),
    (
        "AMD Turion(tm) 64 Mobile Technology MK-36",
        super::Manufacturer::Amd,
        "Turion 64 MK-36",
    ),
    (
        "AMD® Ryzen™5  3450U Quad Core@",
        super::Manufacturer::Amd,
        "Ryzen 5 3450U",
    ),
    ("Apple M1 ", super::Manufacturer::Apple, "M1"),
    (
        "Apple M2 Pro (Virtual)",
        super::Manufacturer::Apple,
        "M2 Pro",
    ),
    (
        "Microsoft SQ2 @ 3.15 GHz",
        super::Manufacturer::Microsoft,
        "",
    ),
    (
        "Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Oryon(TM) CPU",
        super::Manufacturer::Qualcomm,
        "",
    ),
    (
        "Snapdragon (TM) 7c @ 2.40 GHz",
        super::Manufacturer::Qualcomm,
        "",
    ),
    ("MediaTek Dimensity 9200", super::Manufacturer::MediaTek, ""),
    ("Samsung Exynos 2100", super::Manufacturer::Samsung, ""),
    ("Unknown CPU", super::Manufacturer::Unknown, ""),
];

#[cfg(test)]
pub(crate) const TIER_CPU_INFO_TESTS: &[(i32, &str, super::PerformanceTier)] = &[
    (
        -42,
        "Some imaginary processor",
        super::PerformanceTier::Unknown,
    ),
    (0, "Some unknown processor", super::PerformanceTier::Unknown),
    (
        1,
        "Intel(R) Celeron(R) CPU          450  @ 2.20GHz",
        super::PerformanceTier::Low,
    ),
    (
        1,
        "AMD Athlon(tm) Processor 1640B",
        super::PerformanceTier::Low,
    ),
    (
        2,
        "AMD E2-9000e RADEON R2, 4 COMPUTE CORES 2C+2G",
        super::PerformanceTier::Low,
    ),
    (
        2,
        "AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G",
        super::PerformanceTier::Low,
    ),
    (
        2,
        "AMD Athlon(tm) 64 X2 Dual Core Processor 5000+",
        super::PerformanceTier::Low,
    ),
    (
        4,
        "AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx",
        super::PerformanceTier::Mid,
    ),
    (
        4,
        "AMD Ryzen 3 3100 4-Core Processor",
        super::PerformanceTier::High,
    ),
    (
        2,
        "Intel(R) Atom(TM) CPU Z520   @ 1.33GHz",
        super::PerformanceTier::Low,
    ),
    (
        2,
        "Intel(R) Celeron(R) CPU J3355 @ 2.00GHz",
        super::PerformanceTier::Low,
    ),
    (
        2,
        "Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz",
        super::PerformanceTier::Low,
    ),
    (
        2,
        "Intel(R) Pentium(R) CPU        P6100  @ 2.00GHz",
        super::PerformanceTier::Low,
    ),
    (
        2,
        "Intel(R) Celeron(R) CPU B830 @ 1.80GHz",
        super::PerformanceTier::Low,
    ),
    (
        2,
        "Intel(R) Celeron(R) N4000 CPU @ 1.10GHz",
        super::PerformanceTier::Mid,
    ),
    (
        4,
        "Intel(R) Celeron(R) CPU  N3160  @ 1.60GHz",
        super::PerformanceTier::Low,
    ),
    (4, "Intel(R) N100", super::PerformanceTier::High),
    (4, "Intel(R) Atom(TM) x7425E", super::PerformanceTier::High),
    (
        8,
        "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz",
        super::PerformanceTier::High,
    ),
    (
        8,
        "Intel(R) Core(TM) Ultra 5 226V",
        super::PerformanceTier::Ultra,
    ),
    (
        16,
        "Intel(R) Core(TM) Ultra 7 155H",
        super::PerformanceTier::Ultra,
    ),
    (6, "Apple A18 Pro", super::PerformanceTier::High),
    (8, "Apple M1", super::PerformanceTier::Ultra),
    (
        10,
        "Snapdragon(R) X Plus - X1P64100 - Qualcomm(R) Oryon(TM) CPU",
        super::PerformanceTier::High,
    ),
    (
        12,
        "Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Oryon(TM) CPU",
        super::PerformanceTier::Ultra,
    ),
    (8, "MediaTek Dimensity 9200", super::PerformanceTier::High),
    (8, "Samsung Exynos 2100", super::PerformanceTier::High),
    (2, "Unknown CPU", super::PerformanceTier::Low),
    (4, "Unknown CPU", super::PerformanceTier::Mid),
    (8, "Unknown CPU", super::PerformanceTier::High),
    (16, "Unknown CPU", super::PerformanceTier::Ultra),
];
